export const COURSES={
    "3":{
    "A":[
    {
    id:0,
    subname:'MATHS',
    subcode:'18CS031',
    teacher_id:9,
    },
    {
    id:1,
    subname:'DSA',
    subcode:'18CS032',
    teacher_id:2,
    },
    {
    id:2,
    subname:'ADE',
    subcode:'18CS033',
    teacher_id:3,
    },
    {
    id:3,
    subname:'CO',
    subcode:'18CS034',
    teacher_id:6,
    },
    {
    id:0,
    subname:'SE',
    subcode:'18CS035',
    teacher_id:7,
    },
    {
    id:0,
    subname:'DMS',
    subcode:'18CS036',
    teacher_id:6,
    },
    {
    id:0,
    subname:'DSA_LAB',
    subcode:'18CSL037',
    teacher_id:2,
    },
    {
    id:0,
    subname:'ADE_LAB',
    subcode:'18CSL038',
    teacher_id:3,
    
    },
    ],
    "B":[
        {
        id:0,
        subname:'MATHS',
        subcode:'18CS031',
        teacher_id:9,
        },
        {
        id:1,
        subname:'DSA',
        subcode:'18CS032',
        teacher_id:2,
        },
        {
        id:2,
        subname:'ADE',
        subcode:'18CS033',
        teacher_id:3,
        },
        {
        id:3,
        subname:'CO',
        subcode:'18CS034',
        teacher_id:6,
        },
        {
        id:0,
        subname:'SE',
        subcode:'18CS035',
        teacher_id:7,
        },
        {
        id:0,
        subname:'DMS',
        subcode:'18CS036',
        teacher_id:6,
        },
        {
        id:0,
        subname:'DSA_LAB',
        subcode:'18CSL037',
        teacher_id:2,
        },
        {
        id:0,
        subname:'ADE_LAB',
        subcode:'18CSL038',
        teacher_id:3,
        
        },
        ]
},
    '4':{
        'A':[
            {
            id:0,
            subname:'MATHS',
            subcode:'18CS041',
            teacher_id:9,
            },
            {
            id:1,
            subname:'DAA',
            subcode:'18CS042',
            teacher_id:4,
            },
            {
            id:2,
            subname:'OS',
            subcode:'18CS043',
            teacher_id:7,
            },
            {
            id:3,
            subname:'MES',
            subcode:'18CS034',
            teacher_id:8,
            },
            {
            id:0,
            subname:'OOC',
            subcode:'18CS035',
            teacher_id:5,
            },
            {
            id:0,
            subname:'DC',
            subcode:'18CS036',
            teacher_id:3,
            },
            {
            id:0,
            subname:'DAA_LAB',
            subcode:'18CSL037',
            teacher_id:5,
            },
            {
            id:0,
            subname:'MES_LAB',
            subcode:'18CSL038',
            teacher_id:8,
            
            },
            ],
            'B':[
            {
            id:0,
            subname:'MATHS',
            subcode:'18CS041',
                    teacher_id:9,
                    },
                    {
                    id:1,
                    subname:'DAA',
                    subcode:'18CS042',
                    teacher_id:4,
                    },
                    {
                    id:2,
                    subname:'OS',
                    subcode:'18CS043',
                    teacher_id:7,
                    },
                    {
                    id:3,
                    subname:'MES',
                    subcode:'18CS034',
                    teacher_id:8,
                    },
                    {
                    id:0,
                    subname:'OOC',
                    subcode:'18CS035',
                    teacher_id:5,
                    },
                    {
                    id:0,
                    subname:'DC',
                    subcode:'18CS036',
                    teacher_id:3,
                    },
                    {
                    id:0,
                    subname:'DAA_LAB',
                    subcode:'18CSL037',
                    teacher_id:5,
                    },
                    {
                    id:0,
                    subname:'MES_LAB',
                    subcode:'18CSL038',
                    teacher_id:8,
                    
                    },
                    ]
                    },                
        
    }