export const USERS=[
    {
    id:0,
    name:'Eshan Singh Parihar',
    email:'eshan.18cs036@cambridge.edu.in',
    password:'1cd18cs036',
    sem:'4',
    section:'B',
    usn:'1cd18cs036',
    teacher:false,
    student:true,
    branch:'cse',
    },
    {
    id:1,
    name:'Dev Gupta',
    email:'dev.18cs034@cambridge.edu.in',
    password:'1cd18cs034',
    sem:'3',
    section:'A',
    usn:'1cd18cs034',
    teacher:false,
    student:true,
    branch:'cse',
    },
    {
    id:2,
    name:'Mrs.Geetha',
    email:'teacher1@cambridge.edu.in',
    password:'teacher1',
    teacher:true,
    student:false,
    branch:'cse',
    },
    {
    id:3,
    name:'Mr .Sandeep',
    email:'teacher2@cambridge.edu.in',
    password:'teacher2',
    teacher:true,
    student:false,
    branch:'cse',
    },
    {
    id:4,
    name:'Mr .Janardhan Singh',
    email:'teacher3@cambridge.edu.in',
    password:'teacher3',
    teacher:true,
    student:false,
    branch:'cse',
    },
    {
    id:5,
    name:'Mr .Pushpanathan',
    email:'teacher4@cambridge.edu.in',
    password:'teacher4',
    teacher:true,
    student:false,
    branch:'cse',
    },
    {
    id:6,
    name:'Mr .Jayanthi',
    email:'teacher5@cambridge.edu.in',
    password:'teacher5',
    teacher:true,
    student:false,
    branch:'cse',
    },
    {
    id:7,
    name:'Mr .Manikandan',
    email:'teacher6@cambridge.edu.in',
    password:'teacher6',
    teacher:true,
    student:false,
    branch:'cse',
    },
    {
    id:8,
    name:'Mrs. Jayanthi MG',
    email:'teacher7@cambridge.edu.in',
    password:'teacher7',
    teacher:true,
    student:false,
    branch:'cse',
    },
    {
    id:9,
    name:'Mr. Kiran Gowda',
    email:'teacher8@cambridge.edu.in',
    password:'teacher8',
    teacher:true,
    student:false,
    branch:'cse',
    },
    {
        id:10,
        name:'Eshan Singh Parihar',
        email:'Abc',
        password:'Abc',
        sem:'4',
        section:'B',
        usn:'1cd18cs036',
        teacher:false,
        student:true,
        branch:'cse',
        },
    ]
    